config/routes.rb
Mk::Application.routes.draw do
  resources :volume_snapshots
  resources :server_snapshots
  resources :volumes do
    member do
      post 'attach'
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match "page/:action" => "page"
  resources :tenants do
    resources :flavors
    resources :images
    resources :servers do
      member do 
        get "create_snapshot"
        post "make_snapshot"
      end
    end
    resources :volumes
    resources :volume_snapshots
    resources :users
  resources :server_snapshots
    match "/quotas/edit" => "quotas#edit"
    resources :snapshots
    resources :users do
member do 
get :roles
end
    end
  end
  resources :tenants

  resources :flavors

  resources :images

  resources :servers do
    member do 
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match 'users/check'=> "users#check"
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/login' => 'user_sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  resource :user_sessions

  resources :users
  
  namespace :admin do
    root :to => 'users#index'
    resource :users
  end

   root :to => 'user_sessions#new'

end

app/models/server.rb
class Server
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_filter :login_required
  # GET /servers
  # GET /servers.json
  def index
    @servers = compute.servers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server =  compute.get_server(params[:id])
    @server_detail = compute.get_server_detail(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = compute.get_server_detail(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    #:name        => 'NewServer',
      #        :imageRef    => 'http://172.19.0.3/v1.1/images/3',
      #        :flavorRef   => 'http://172.19.0.3/v1.1/flavors/1',
      #        :metadata    => {'Racker' => 'Fanatical'},
      #        :personality => {'/home/bob/wedding.jpg' => '/root/wedding.jpg'})
    @server = compute.create_server(:name=>params[:name],:imageRef=>params[:imageRef],:flavorRef=>params[:flavorRef])

    respond_to do |format|

        format.html { redirect_to servers_path, :notice => 'Server was successfully created.' }
        format.json { render :json => @server, :status => :created, :location => @server }
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = compute.get_server(params[:id]).update(:name=>params[:name])
    respond_to do |format|
        format.html { redirect_to servers_path, :notice => 'Server was successfully updated.' }
        format.json { head :ok }
    end
  end
  def create_snapshot
    @server = compute.get_server_detail(params[:id])
  end
def make_snapshot
  @server = compute.get_server(params[:id]).create_image(:name => params[:name])
   redirect_to server_snapshots_path
end
  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = compute.get_server(params[:id])
    @server.delete!

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.haml
= form_tag('/servers') do
  .field
    = label_tag :name
    %br/
    = text_field_tag  :name
  .field
    = label_tag :metadata
    %br/
    = text_area_tag :metadata
  .field
    = label_tag :imageRef
    %br/
    = select_tag "imageRef", options_for_select(glance.images.collect{|image| [ image[:name], image[:id] ]})
  .field
    = label_tag :flavorRef
    %br/
    = select_tag "flavorRef", options_for_select(compute.flavors.collect{|p| [ p[:name]+"#{p[:vcpus]} VCPU / #{p[:disk]} GB Dish / #{p[:ram]} MB Ram", p[:links][0][:href].split("/").last]})
  .actions
    = submit_tag "submit",:class=>"btn btn-primary"
- content_for :javascripts do
  :javascript
  $(window).load(function(){
      var imageRef = $.fn.url().param("imageRef")
       if (imageRef != undefined){
       $("option[value='"+imageRef +"']").attr("selected","selected")
       }
  }); 
    

app/views/servers/create_snapshot.haml
= form_tag("/servers/#{@server[:id]}/make_snapshot") do
  .field
    = label_tag :snapshot_name
    %br/
    = text_field_tag  :name
  .actions
    = submit_tag "create snapshot",:class=>"btn btn-primary"

app/views/servers/edit.haml
%h1 Editing server
= form_tag("/servers/#{@server[:id]}",:method=>"PUT") do
  .field
    = label_tag :name
    %br/
    = text_field_tag  :name,@server[:name]
  .actions
    = submit_tag "update",:class=>"btn btn-primary"
= link_to 'Show', @server
|
\#{link_to 'Back', servers_path}

app/views/servers/index.haml
%h1 listing servers
.table_wrapper
  %table#instances.table.table-bordered.table-striped
    %thead
      %tr
        %th Tenant
        %th User
        %th Instance ID
        %th Host
        %th Instance Name
        %th IP Address
        %th Size
        %th Status
        %th Task
        %th Power State
        %th.actions_column Actions
    %tbody
      - @servers.each do |server|
        %tr.status_up
          -real_server = compute.get_server(server[:id])
          -server_detail = compute.get_server_detail(server[:id])
          -flavor =compute.flavors.select{|c| c["id"]==real_server.flavor["id"]}[0]
          %td
            = server_detail["tenant_id"]
            (
            = keystone.get_tenant(server_detail["tenant_id"])[:name]
            )
          %td= server_detail[:user_id]
          %td= server_detail[:id]+"(#{server_detail['OS-EXT-SRV-ATTR:instance_name']})"
          %td= server_detail["OS-EXT-SRV-ATTR:host"]
          %td= link_to real_server.name, server_path(:id=>real_server.id)
          %td= real_server.addresses[0].try(:address)
          %td= flavor[:name]+"#{flavor[:vcpus]} VCPU / #{flavor[:disk]} GB Dish / #{flavor[:ram]} MB Ram"
          %td= real_server.status
          %td=server_detail["OS-EXT-STS:task_state"].nil?? "No":server_detail["OS-EXT-STS:task_state"]
          %td=server_detail["OS-EXT-STS:power_state"] == 1 && "running" || "No status"
          %td.actions_column
            .btn-group
              %a.ajax-modal.btn.btn-small{:href => ""} actions
              %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %span.caret
              %ul.dropdown-menu.row_actions.clearfix
                %li.clearfix
                  =link_to "edit",edit_server_path(:id=>server[:id]),:class=>"btn btn-small"
                -if server_detail["OS-EXT-STS:power_state"]==1
                  %li.clearfix
                    %a.btn.btn-small{:href => "#{compute.get_console(server_detail[:id]) }",:target=>"_blank"} VNC Console
                %li.clearfix
                  =link_to "Snapshot" ,create_snapshot_server_path(:id=>server_detail[:id]),:class=>"ajax-modal btn btn-small"
    %tfoot
      %tr
        %td{:colspan => "12"}
          %span
            ="Displaying #{@servers.size} item"
  = link_to 'New Server', new_server_path

app/views/servers/new.haml
%h1 New server
= render 'form'
= link_to 'Back', servers_path

app/views/servers/show.haml
.row-fluid
  .span12
    %ul#instance_details.nav.nav-tabs.ajax-tabs
      %li.active
        %a{"data-loaded" => "true", "data-target" => "#instance_details__overview", "data-toggle" => "tab", :href => "?tab=instance_details__overview"} Overview
      %li
        %a{"data-loaded" => "false", "data-target" => "#instance_details__log", "data-toggle" => "tab", :href => "?tab=instance_details__log"} Log
      %li
        %a{"data-loaded" => "false", "data-target" => "#instance_details__vnc", "data-toggle" => "tab", :href => "?tab=instance_details__vnc"} VNC
    .tab-content
      #instance_details__overview.tab-pane.active
        %h3 Instance Overview
        .status.row-fluid
          %h4 Status
          %hr.header_rule
            %ul
              %li
                %strong Status:
                =@server.status
              %li
                %strong Instance Name:
                =@server.name
              %li
                %strong> Instance ID:
                =@server_detail[:id]
        .specs.row-fluid
          %h4 Specs
          -flavor =compute.flavors.select{|c| c["id"]==@server.flavor["id"]}[0]
          %hr.header_rule
            %ul
              %li
                %strong> RAM:
                =flavor[:ram] 
                MB
              %li
                %strong> VCPUs:
                =flavor[:vcpus]
                VCPU
              %li
                %strong> Disk:
                =flavor[:disk]
                GB
        .addresses.row-fluid
          %h4 IP Addresses
          %hr.header_rule
            %ul
              -@server.addresses.each do |addr|
                %li
                  %strong
                    =addr.label
                  =addr.address
        .security_groups.row-fluid
          %h4 Security Groups
          %hr.header_rule
            %ul
              %li
                %strong default
                %ul
                  %li
                    %em No rules defined.
        .meta.row-fluid
          %h4 Meta
          %hr.header_rule
            %ul
              %li
                %strong> Key name:
                \ 
                %em None
              %li
                %strong> Image Name:
                \ cirros-0.3.0-x86_64-blank
        .volumes.row-fluid
          %h4 Volumes
          %hr.header_rule
            %ul
              %li
                %em No volumes attached.
      #instance_details__log.tab-pane
      #instance_details__vnc.tab-pane