config/routes.rb
Mk::Application.routes.draw do
  resources :volume_snapshots
  resources :server_snapshots
  resources :volumes do
    member do
      post 'attach'
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match "page/:action" => "page"
  resources :tenants do
    resources :flavors
    resources :images
    resources :servers do
      member do 
        get "create_snapshot"
        post "make_snapshot"
      end
    end
    resources :volumes
    resources :volume_snapshots
    resources :users
  resources :server_snapshots
    match "/quotas/edit" => "quotas#edit"
    resources :snapshots
    resources :users do
member do 
get :roles
end
    end
  end
  resources :tenants

  resources :flavors

  resources :images

  resources :servers do
    member do 
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match 'users/check'=> "users#check"
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/login' => 'user_sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  resource :user_sessions

  resources :users
  
  namespace :admin do
    root :to => 'users#index'
    resource :users
  end

   root :to => 'user_sessions#new'

end

app/models/user.rb
class User
#  include Privilege
#  class NotAuthorized < StandardError
#  end

#  class MyCryptoProvider
    # Turns your raw password into a Sha1 hash.
#    def self.encrypt(*tokens)
#      digest = Digest::SHA1.hexdigest("--#{tokens[1]}--#{tokens[0]}--")
#      digest
#    end

    # Does the crypted password match the tokens? Uses the same tokens that were used to encrypt.
#    def self.matches?(crypted, *tokens)
#      encrypt(*tokens) == crypted
#    end
#  end

#  acts_as_authentic do |c|
    #    c.transition_from_crypto_providers= ::MyCryptoProvider
    #    c.crypto_provider = Authlogic::CryptoProviders::Sha512
# #   c.login_field = :login
#    c.crypto_provider = MyCryptoProvider
#    c.disable_perishable_token_maintenance true
#  end
  #  attr_accessible :login, :email, :password, :password_confirmation

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/models/user/privilege.rb
module User::Privilege
  extend ActiveSupport::Concern
  included do
    has_and_belongs_to_many :roles
  end

  def guest?
    id == 0
  end
  alias anonymous? guest?

  def role_names
    roles.collect{|r|r.name}.join(' ')
  end
  # has_role? simply needs to return true or false whether a user has a role or not.
  # It may be a good idea to have "admin" roles return true always

  def has_role?(role_in_question)
    @_list ||= self.role_names
    return true if @_list.include?("admin")
    (@_list.include?(role_in_question.to_s) )
  end

  def is_admin?
    !guest? && has_role?('admin')
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_filter :login_required
  require_role "admin"
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required
  def index
    if params[:tenant_id] 
       @users = keystone.get_users_for_tenant(params[:tenant_id])
    else
          @users = keystone.users
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tenants }
    end
  end
  def roles
  if  (params[:tenant_id] && params[:id])
   @roles = keystone.get_user_roles_for_tenant(params[:id],params[:tenant_id])
  end
  end
  def new
    @user = User.new
  end
   {"authenticity_token"=>
    "tet8RxJVJa7TsUuYk/snz/FrPdG/HfWY94DCyLa4doY=",
     "enabled"=>"yes", 
     "name"=>"asdf", 
     "tenantId"=>"2d5145ccf4b34cbbaa5e9a5059123f48", 
     "commit"=>"submit", "password_confirm"=>"[FILTERED]", 
     "password"=>"[FILTERED]", "
     email"=>"asdf",
      "utf8"=>"✓"}

  def create
    if params[:password] == params[:password_confirm] 
      keystone.create_user(:name=>params[:name],:email=>params[:email],:password=>params[:password],:tenantId=>params[:tenantId],:enabled=>true)
    end
    redirect_to users_path
  end
  def destroy
    keystone.delete_user(params[:id])
    redirect_to users_path
  end
  def show
    @user = keystone.get_user(params[:id])
  end

  def edit
    @user = keystone.get_user(params[:id])
  end
  
  def update
     keystone.update_user(:id=>params[:id],:name=>params[:name],:email=>params[:email],:password=>params[:password],:tenantId=>params[:tenantId],:enabled=>true)
     redirect_to users_path
  end
  def check
    if params[:check_name] == "login"
      check_login
    else
      check_email
     end
   end
    def check_login
      user=User.find_by_login(params[:check_area])
      if !user
        return render  :json=>{:success_message=>"可以使用"}
      else
        return render  :json=> {:error_message=>"用户名已经被使用"}
      end
    end

    def check_email
      user=User.find_by_email(params[:check_area])
      if user
        return render  :json=> {:error_message=>"邮箱已经被使用"}
      else
        return render  :json=> {:success_message=>"可以使用"}
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.haml
= form_tag("/users/#{@user[:id]}",:method=>"PUT") do
  .field
    = label_tag :name
    %br/
    = text_field_tag  :name,@user[:name]
  .field
    = label_tag :email
    %br/
    = text_area_tag :email,@user[:email]
  .field
    = label_tag :password
    %br/
    = password_field_tag :password
  .field
    = label_tag :password_confirm
    %br/
    = password_field_tag :password_confirm
  .field
    = label_tag :tenantId
    %br/
    = select_tag "tenantId", options_for_select(keystone.tenants.collect{|tenant| [ tenant[:name], tenant[:id] ]})
  -#.field
    = label_tag :enabled
    %br/
    =check_box_tag "enabled",true,true
  .actions
    = submit_tag "submit",:class=>"btn btn-primary"
- content_for :javascripts do
  :javascript
  $(window).load(function(){
       var imageRef = $.fn.url().param("imageRef")
       if (imageRef != undefined){
       $("option[value='"+imageRef +"']").attr("selected","selected")
       }
  }); 

app/views/users/index.haml
%h1 Listing users
.table_wrapper
  %table#instances.table.table-bordered.table-striped
    %thead
      %tr
        %th id
        %th Name
        %th Email
        %th Enabled
        %th.actions_column Actions
    %tbody
      - @users.each do |user|
        %tr.status_up
          %td=user[:id]
          %td=user[:name]
          %td=user[:email]
          %td=user[:enabled]
          %td.actions_column
            .btn-group
              %a.ajax-modal.btn.btn-small{:href => ""} actions
              %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %span.caret
              %ul.dropdown-menu.row_actions.clearfix
                %li.clearfix
                  =link_to "edit",edit_user_path(:id=>user[:id]),:class=>"btn btn-small"
                %li.clearfix
                  =link_to "delete",user_path(:id=>user[:id]), :confirm => 'Are you sure?', :method => :delete,:class=>"btn btn-small"
=link_to "create new user",new_user_path             

app/views/users/new.haml
= form_tag('/users') do
  .field
    = label_tag :name
    %br/
    = text_field_tag  :name
  .field
    = label_tag :email
    %br/
    = text_area_tag :email
  .field
    = label_tag :password
    %br/
    = password_field_tag :password
  .field
    = label_tag :password_confirm
    %br/
    = password_field_tag :password_confirm
  .field
    = label_tag :tenantId
    %br/
    = select_tag "tenantId", options_for_select(keystone.tenants.collect{|tenant| [ tenant[:name], tenant[:id] ]})
  .field
    = label_tag :enabled
    %br/
    =check_box_tag "enabled",true,true
  .actions
    = submit_tag "submit",:class=>"btn btn-primary"

app/views/users/roles.haml
%h1 Listing roles
.table_wrapper
  %table#instances.table.table-bordered.table-striped
    %thead
      %tr
        %th id
        %th Name
        %th Email
        %th Enabled
        %th actions_column
    %tbody
      %tr.status_up
        %td=1

app/views/users/show.haml
-if logged_in?
  =current_user.login
  =link_to "登出", logout_path
  
-else
  =link_to "请登录", login_path