config/routes.rb
Mk::Application.routes.draw do
  resources :volume_snapshots
  resources :server_snapshots
  resources :volumes do
    member do
      post 'attach'
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match "page/:action" => "page"
  resources :tenants do
    resources :flavors
    resources :images
    resources :servers do
      member do 
        get "create_snapshot"
        post "make_snapshot"
      end
    end
    resources :volumes
    resources :volume_snapshots
    resources :users
  resources :server_snapshots
    match "/quotas/edit" => "quotas#edit"
    resources :snapshots
    resources :users do
member do 
get :roles
end
    end
  end
  resources :tenants

  resources :flavors

  resources :images

  resources :servers do
    member do 
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match 'users/check'=> "users#check"
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/login' => 'user_sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  resource :user_sessions

  resources :users
  
  namespace :admin do
    root :to => 'users#index'
    resource :users
  end

   root :to => 'user_sessions#new'

end

app/models/volume.rb
class Volume 
  
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
  before_filter :login_required
  # GET /volumes
  # GET /volumes.json
  def index
    @volumes = compute.list_volumes

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @volumes }
    end
  end

  # GET /volumes/1
  # GET /volumes/1.json
  def show
    @volume = compute.get_volume(params[:id].to_i)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @volume }
    end
  end

  # GET /volumes/new
  # GET /volumes/new.json
  def new
    @volume = Volume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @volume }
    end
  end

  # GET /volumes/1/edit
  def edit
    @volume = compute.get_volume(params[:id])
  end

  def attach
     compute.create_attachment(params[:server_id],params[:volumeId],params[:attachment]) 
     respond_to do |format|
      format.html { redirect_to volumes_path, :notice => 'attachment was successfully created.' }
      format.json { render :json => @volume, :status => :created, :location => @volume }
    end
  end

  def create_snapshot
    @volume = compute.get_volume(params[:id])
  end
 #{"snapshot": {"display_name": "display_nameeeee", "force": false, "display_description": "descriptionnnnnnn", "volume_id": 2}}'

  def make_snapshot
    @server = compute.create_snapshot(:display_name=>params[:name],:force=>true,:display_description=>params[:description],:volume_id=>params[:id])
    redirect_to volume_snapshots_path
  end

  # POST /volumes
  # POST /volumes.json
  def create
    @volume = compute.create_volume({"size"=>params[:size],"display_name"=>params[:name],"display_description"=>params[:description]})


    respond_to do |format|
        format.html { redirect_to @volume, :notice => 'Volume was successfully created.' }
        format.json { render :json => @volume, :status => :created, :location => @volume }
    end
  end

  # PUT /volumes/1
  # PUT /volumes/1.json
  def update
    @volume = Volume.find(params[:id])

    respond_to do |format|
      if @volume.update_attributes(params[:volume])
        format.html { redirect_to @volume, :notice => 'Volume was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @volume.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /volumes/1
  # DELETE /volumes/1.json
  def destroy
    compute.delete_volume(params[:id].to_i)

    respond_to do |format|
      format.html { redirect_to volumes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/volumes/_form.haml
= form_tag('/volumes') do
  .field
    = label_tag :name
    %br/
    = text_field_tag  :name
  .field
    = label_tag :description
    %br/
    = text_area_tag :description
  .field
    = label_tag :size
    %br/
    = text_field_tag  :size
  .actions
    = submit_tag "submit",:class=>"btn btn-primary"

app/views/volumes/create_snapshot.haml
= form_tag("/volumes/#{@volume[:id]}/make_snapshot") do
  .field
    = label_tag :name
    %br/
    = text_field_tag  :name
  .field
    = label_tag :description
    %br/
    = text_field_tag  :description
  .actions
    = submit_tag "create snapshot",:class=>"btn btn-primary"

app/views/volumes/edit.haml
= form_tag("/volumes/#{params[:id]}/attach") do
  =hidden_field_tag "volumeId",params[:id]
  .field
    = label_tag :server_id
    %br/
    = select_tag "server_id", options_for_select(compute.servers.collect{|server| [ server[:name], server[:id] ]})
  .field
    = label_tag :attachment
    %br/
    = text_field_tag :attachment ,"/dev/vdc"
  .actions
    = submit_tag "attach",:class=>"btn btn-primary"

app/views/volumes/index.haml
%h1 Listing volumes
.table_wrapper
  %table#instances.table.table-bordered.table-striped
    %thead
      %tr
        %th Name
        %th Description
        %th size
        %th status
        %th attachments
        %th.actions_column Actions
    %tbody
      - @volumes.each do |volume|
        %tr
          %td=link_to  volume[:displayName],volume_path(:id=>volume[:id])
          %td= volume[:displayDescription]
          %td= volume[:size]
          %td= volume[:status]
          %td
            -volume["attachments"].each do |attachment|
              =link_to "#{attachment["serverId"]}","/servers/#{attachment["serverId"]}"
          -#%td= link_to "#{volume["attachments"][0][:serverId]}", "servers/"+ volume["attachments"][0]["serverId"]
          %td.actions_column
            .btn-group
              %a.ajax-modal.btn.btn-small{:href => ""} actions
              %a.btn.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %span.caret
              %ul.dropdown-menu.row_actions.clearfix
                %li.clearfix
                  =link_to "delete",volume_path(:id=>volume[:id]), :confirm => 'Are you sure?', :method => :delete,:class=>"btn btn-small"
                %li.clearfix
                  =link_to "attach",edit_volume_path(:id=>volume[:id]),:class=>"btn btn-small"
                  =link_to "create_snapshot",create_snapshot_volume_path(:id=>volume[:id]),:class=>"btn btn-small"
                  
          
= link_to 'New Volume', new_volume_path

app/views/volumes/new.haml
%h1 New volume
= render 'form'
= link_to 'Back', volumes_path

app/views/volumes/new.html.erb
%h1 New volume
= render 'form'
= link_to 'Back', volumes_path

app/views/volumes/show.haml
%p#notice= notice
%ul#instance_tabs
  %li.active
    %a.overview{:href => "#"} Overview
.dash_block
  #overview.tab_wrapper
    %ul
      %li
        .status
          %h4 Details
          %ul
            %li
              %span ID:
              = @volume[:id]
            %li
              %span Name:
              = @volume[:displayName]
            %li
              %span Size:
              = @volume[:size]
            %li
              %span Description:
              = @volume[:displayDescription]
            %li
              %span Status:
              = @volume[:status]
            %li
              %span Created:
              = @volume[:createdAt]
            %li
              %span Attached To:
              - @volume[:attachments].each do |attachment|
                %a{:href => "/servers/\#{attachment[:serverId]}"}
                  Instance #{attachment[:serverId]}
                  (first server)
                on #{attachment[:device]}
= link_to 'Edit', edit_volume_path(:id=>@volume[:id])
|
= link_to 'Back', volumes_path