config/routes.rb
Mk::Application.routes.draw do
  resources :volume_snapshots
  resources :server_snapshots
  resources :volumes do
    member do
      post 'attach'
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match "page/:action" => "page"
  resources :tenants do
    resources :flavors
    resources :images
    resources :servers do
      member do 
        get "create_snapshot"
        post "make_snapshot"
      end
    end
    resources :volumes
    resources :volume_snapshots
    resources :users
  resources :server_snapshots
    match "/quotas/edit" => "quotas#edit"
    resources :snapshots
    resources :users do
member do 
get :roles
end
    end
  end
  resources :tenants

  resources :flavors

  resources :images

  resources :servers do
    member do 
      get "create_snapshot"
      post "make_snapshot"
    end
  end

  match 'users/check'=> "users#check"
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/login' => 'user_sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  resource :user_sessions

  resources :users
  
  namespace :admin do
    root :to => 'users#index'
    resource :users
  end

   root :to => 'user_sessions#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include OpenStack
  include AuthenticatedSystem
  before_filter :reload_compute
  def compute
    return @compute if defined?(@compute)
    @compute =  OpenStack::Compute::Connection.new(:username => session[:username], :api_key => session[:api_key], :auth_url => session[:url])
  end
  def reload_compute
    if params[:tenant_id]
      p current_tenant[:name]
      @compute =  OpenStack::Compute::Connection.new(:username => session[:username], :api_key => session[:api_key], :auth_url => session[:url],:authtenant=>current_tenant["name"])
    end
  end
  def keystone
    return @keystone if defined?(@keystone)
    @keystone = OpenStack::Compute::Connection.new(:username => session[:username], :api_key => session[:api_key], :auth_url => session[:url],:keystone=>true) 
#puts cs
#p  JSON.parse(cs.req("get","/users").body)
#p  JSON.parse(cs.req("post","/users",{"user"=>{"id"=>}}).body)
 
  end
  def current_tenant
    if params[:tenant_id]
      OpenStack::Compute.symbolize_keys(keystone.tenants.select{|c| c[:name]==keystone.get_tenant(params[:tenant_id])[:name]}[0])

    elsif @tenant
      tenant = @tenant
    end
  end
  def glance
    return @glance if defined?(@glance)
    @glance =  OpenStack::Compute::Connection.new(:username => session[:username], :api_key => session[:api_key], :auth_url => session[:url],:glance=>true) 
  end
  def require_login
  end
  helper_method :compute,:keystone,:glance,:current_tenant
end

app/helpers/application_helper.rb
module ApplicationHelper
 def body_class_names
    today = Date.today
    [controller.controller_name, "#{controller.controller_name}-#{controller.action_name}",
    "y#{today.year}", "m#{today.month}", "d#{today.day}"
    ]
  end
end

app/views/application/_admin_sidebar.haml
%h4 System Panel
%ul.main_nav
  %li
    =link_to "Tenants",tenants_path,:class=>(controller_name == "tenants" && "active")
  %li
    =link_to "Users",users_path,:class=>(controller_name == "users" && "active")
  %li
    =link_to "Servers",servers_path,:class=>(controller_name == "servers" && "active")
  
  %li
    =link_to "Flavors",flavors_path,:class=>(controller_name == "flavors" && "active")
  %li
    =link_to "Images",images_path,:class=>(controller_name == "images" && "active")
  %li
    =link_to "Volumes",volumes_path,:class=>(controller_name == "volumes" && "active")
  %li
    =link_to "Volume_snapshots","/volume_snapshots",:class=>(controller_name == "volume_snapshots" && "active")
  %li
    =link_to "server_snapshots","/server_snapshots",:class=>(controller_name == "server_snapshots" && "active")
  %li
    =link_to "Services","/page/services",:class=>(action_name == "services" && "active")
  %li
    =link_to "Quotas","/page/quotas",:class=>(action_name == "quotas" && "active")
  

app/views/application/_sidebar.haml
#tenant_switcher.dropdown.switcher_bar{:tabindex => "1"}
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#tenant_switcher"}
    %h4 Project
    %h3 
      =current_tenant["name"]
  %ul#tenant_list.dropdown-menu
    %li.divider
    - keystone.get_tenants_for_user(keystone.current_auth_user[:id]).each do |c|
      %li
        %a{:href => "/tenants/#{c['id']}/servers"}
          =c["name"]
%h4 Manage Compute
%ul.main_nav
  %li
    =link_to "Servers","/tenants/#{current_tenant['id']}/servers",:class=>(controller_name == "servers" && "active")
  %li
    =link_to "Volumes","/tenants/#{current_tenant['id']}/volumes",:class=>(controller_name == "volumes" && "active")
  %li
    =link_to "Volume_snapshots","/tenants/#{current_tenant['id']}/volume_snapshots",:class=>(controller_name == "volume_snapshots" && "active")
  %li
    =link_to "server_snapshots","/tenants/#{current_tenant['id']}/server_snapshots",:class=>(controller_name == "server_snapshots" && "active")